### ISSUE TITLE
Sanitize docker-compose ENVs

### ISSUE THREAD

**Issue by dapplion** [dappnode/DNP_DAPPMANAGER#351]
Alert early when a compose contains variable interpolation and show a nice error
```yaml
  environment:
      Url: 'https://${HOST}'
      Port: 80
      EthereumNodeUrl: '${NODE_URL}'
      RelayHubAddress: '${RELAY_HUB}'
      GasPricePercent: '${GAS_PRICE_PERCENT}'
      BaseFee: '${BASE_FEE}'
      PercentFee: '${PERCENT_FEE}'
      DevMode: '${DEVMODE}'
```
Also deal with an `environments` property that is either in array or object format
