### ISSUE TITLE
dncore_network is not injected to core DNPs

### ISSUE THREAD

**Issue by dapplion** [dappnode/DNP_DAPPMANAGER#591]
When installing a custom core package for testing with docker-compose:
```yaml
version: "3.4"
services:
  dappnodesdk.public.dappnode.eth:
    build: ./build
    image: "dappnodesdk.public.dappnode.eth:0.1.0"
    restart: always
```

```
Error: Command failed: docker-compose -f /usr/src/app/DNCORE/docker-compose-dappnodesdk.yml up --no-start <&-
Some networks were defined but are not used by any service: network
Service "dappnodesdk.public.dappnode.eth" uses an undefined network "dncore_network"

    at Object.<anonymous> (/usr/src/app/webpack:/src/utils/shell.ts:37:16)
    at Generator.throw (<anonymous>)
    at rejected (/usr/src/app/index.js:19429:65)
    at process._tickCallback (internal/process/next_tick.js:68:7)

{
  "name": "dappnodesdk.public.dappnode.eth",
  "version": "/ipfs/QmUc6cPLJVnLGjisK69b7JsgTxUb8kkSQJSJJem1tUKdEP",
  "userSettings": {},
  "options": {
    "BYPASS_CORE_RESTRICTION": true
  }
}
```
