### ISSUE TITLE
Setup wizard: Share variables with multiple services

### ISSUE THREAD

**Issue by TripleSpeeder** [dappnode/DNP_DAPPMANAGER#633]
**Is your feature request related to a problem? Please describe.**
I'm working on a package that consists of multiple services. Each service needs to be provided with the same Ethereum endpoint. I'm using the setup wizard to help people setting this up.

The problem: I need to make separate fields for each service. So the user needs to set up the identical ethereum endpoint 3 times.

**Describe the solution you'd like**

I would like the `service` field to be an array of strings. This way I can specify that a field targets multiple services. Something like this:

```yml
fields:
  - id: ethereum_url
  - target:
    - type: environment
    - name: ETHEREUM_URL
    - services: 
      - "service1"
      - "service2"
      - "service3"
```

As a result the setup wizard will show only one field for specifying ETHEREUM_URL, but this setting will be applied to all services. This requires that all services use the exact same name for the env variable.
