### ISSUE TITLE
Add support for cap_add, cap_drop, network_mode and command

### ISSUE THREAD

**Issue by eduadiez** [dappnode/DNP_DAPPMANAGER#70]
- [cap_add](https://docs.docker.com/compose/compose-file/#cap_add-cap_drop)
- [cap_drop](https://docs.docker.com/compose/compose-file/#cap_add-cap_drop)
- [network_mode](https://docs.docker.com/compose/compose-file/#network_mode)
- [command](https://docs.docker.com/compose/compose-file/#command)

## docker-compose.yml example
```
version: '3.4'
services:
    test.dnp.dappnode.eth:
        ...
        cap_add:
            - SYS_ADMIN
        cap_drop:
            - NET_ADMIN
        network_mode: "host"
        command: "--command"
```
## dappnode_package.json example
```
{
    "name": "",
    "version": "",
    "description": "",
    "avatar": "",
    "type": "",
    "image": {
      "path": "",
      "hash": "",
      "size": "",
      "cap_drop": [
        "SYS_ADMIN"
      ],
      "cap_add": [
        "NET_ADMIN"
      ],
      "network_mode": "host",
      "command": "--command"
    }
  }
```
