### ISSUE TITLE
Dappmanager doesn't assign itself proper alias

### ISSUE THREAD

**Issue by 3alpha** [dappnode/DNP_DAPPMANAGER#785]
**Describe the bug**

Dappmanager doesn't assign itself proper alias, it is missing `my.dappnode` alias.

**Expected behavior**

When inspecting dappmanager container there should be `my.dappnode` alias on dncore_network.
**Screenshots**

**DAppNode version:**
dappmanager.dnp.dappnode.eth: 0.2.40, commit: 6838be01

**Comment by pablomendezroyo** [comment]
- The dappmanager alias was included in commit c6f480cb89c5ce51b3e5c1013fdc58b69236d9e6 (Apr 5)
- Your commit is older (Apr 14) and should have the alias included 
- Alias was included in the compose so it should be added, even the migration should not affect it since it already have it 

I have the aliases propertly added to the dappmanager
![image](https://user-images.githubusercontent.com/41727368/119801370-ee4cea00-bedd-11eb-8fbd-aa22aded1c9c.png)

**Comment by 3alpha** [comment]
This is a critical issue from UX side so we need to figure out what is happening exactly.
Have you restarted your machine since updating to the new version?
Docker inspect for my dappmanager says this:
```
[
    {
        "Id": "b5d4300eddc63dc8476293d4363d199465459e9ee09ba7e9f4fab9c85d6e68b8",
        "Created": "2021-04-16T09:12:36.841738542Z",
        "Path": "docker-entrypoint.sh",
        "Args": [
            "node",
            "index"
        ],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 1530376,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2021-04-16T09:12:37.754248849Z",
            "FinishedAt": "0001-01-01T00:00:00Z"
        },
        ...
]
```
Which probably means that it has been runing since update (April 16). 
Maybe I should try restarting dappmanager container and then see if it shows up? What are your thoughts? That way we may trigger inclusion of alias and we will know how to fix it.

**Comment by dapplion** [comment]
@3alpha Can you dump the dappmanager's compose here?

**Comment by 3alpha** [comment]
It doesn't have `my.dappnode` alias:
```
version: '3.5'
services:
  dappmanager.dnp.dappnode.eth:
    container_name: DAppNodeCore-dappmanager.dnp.dappnode.eth
    dns: 172.33.1.2
    environment:
      - LOG_LEVEL=info
      - ETH_MAINNET_RPC_URL_OVERRIDE
      - ETH_MAINNET_RPC_URL_REMOTE
      - IPFS_HOST
      - DISABLE_UPNP
    image: 'dappmanager.dnp.dappnode.eth:0.2.40'
    logging:
      driver: journald
    networks:
      dncore_network:
        ipv4_address: 172.33.1.7
        aliases:
          - dappmanager.dappnode
    restart: always
    volumes:
      - '/run/dbus/system_bus_socket:/run/dbus/system_bus_socket'
      - 'dappmanagerdnpdappnodeeth_data:/usr/src/app/dnp_repo'
      - '/usr/src/dappnode/DNCORE:/usr/src/app/DNCORE'
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '/etc/hostname:/etc/dappnodename:ro'
    labels:
      dappnode.dnp.dnpName: dappmanager.dnp.dappnode.eth
      dappnode.dnp.version: 0.2.40
      dappnode.dnp.serviceName: dappmanager.dnp.dappnode.eth
      dappnode.dnp.dependencies: '{}'
      dappnode.dnp.avatar: /ipfs/QmfTpBLzoSdrG88ETRnDus27DTDRUrTXyyVmhXDuMNYVaN
      dappnode.dnp.isCore: 'true'
      dappnode.dnp.default.environment: >-
        ["LOG_LEVEL=info","ETH_MAINNET_RPC_URL_OVERRIDE","ETH_MAINNET_RPC_URL_REMOTE","IPFS_HOST","DISABLE_UPNP"]
      dappnode.dnp.default.volumes: >-
        ["/run/dbus/system_bus_socket:/run/dbus/system_bus_socket","dappmanagerdnpdappnodeeth_data:/usr/src/app/dnp_repo/","/usr/src/dappnode/DNCORE/:/usr/src/app/DNCORE/","/var/run/docker.sock:/var/run/docker.sock","/etc/hostname:/etc/dappnodename:ro"]
volumes:
  dappmanagerdnpdappnodeeth_data: {}
networks:
  dncore_network:
    external
```
