### ISSUE TITLE
Core package multiservice got deleted restart-policy (wireguard)

### ISSUE THREAD

**Issue by pablomendezroyo** [dappnode/DNP_DAPPMANAGER#803]
After installing wireguard package it with the the compose:
```
version: "3.5"
services:
  wireguard:
    build: .
    image: "wireguard.wireguard.dnp.dappnode.eth:0.1.0"
    container_name: DAppNodeCore-wireguard.wireguard.dnp.dappnode.eth
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PEERS=dappnode_admin
      - SERVERURL=
      - WIREGUARD_RELEASE=
      - PUID=1000
      - PGID=1000
      - SERVERPORT=51820
      - "PEERDNS=172.33.1.2,10.20.0.2"
      - INTERNAL_SUBNET=10.24.0.0
      - "ALLOWEDIPS=172.33.0.0/16,10.20.0.0/24"
    volumes:
      - "wg-config:/config"
      - "/lib/modules:/lib/modules"
    ports:
      - "51820:51820/udp"
    networks:
      dncore_network:
        aliases:
          - wireguard.wireguard.dappnode
  api:
    build: ./api
    restart: unless-stopped
    image: "api.wireguard.dnp.dappnode.eth:0.1.0"
    container_name: DAppNodeCore-api.wireguard.dnp.dappnode.eth
    volumes:
      - "wg-config:/config"
    networks:
      dncore_network:
        aliases:
          - api.wireguard.dappnode
volumes:
  wg-config: {}
networks:
  dncore_network:
    name: dncore_network
    external: true
```

The restart policy of the `api` service is deleted by the dappmanager, this results in a container with no restart policy which will prevent the container from start on boots. The compose after the dappmanager parseSafeCompose

```
  api:
    image: 'api.wireguard.dnp.dappnode.eth:0.1.0'
    container_name: DAppNodeCore-api.wireguard.dnp.dappnode.eth
    volumes:
      - 'wg-config:/config'
    networks:
      dncore_network:
        aliases:
          - api.wireguard.dappnode
```

SOLUTION

Allow core packages multi services to define restart policy
